[tools]
java = "latest"
rust = "latest"
node = "latest"
python = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
dart = "latest"
docker-cli = "latest"
docker-compose = "latest"


# CLI tools
chezmoi = "latest"
ripgrep = "latest"
bat = "latest"
fd = "latest"
eza = "latest"
delta = "latest"
dust = "latest"
duf = "latest"
fzf = "latest"
zoxide = "latest"
lazygit = "latest"
lazydocker = "latest"
gping = "latest"
bottom = "latest"
atuin = "latest"
yazi = "latest"
zellij = "latest"
"cargo:procs" = "latest"
"cargo:tokei" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
python.github_attestations = false
github_attestations = false
